/**
 * PRESIDIN — Real-time WebSocket service
 *
 * Broadcasts:
 *  - signals:new       (new signal generated by MasterAgent)
 *  - tick:update        (live tick from Deriv)
 *  - anomaly:alert      (Anomaly Guard triggered)
 *  - drift:alert        (Drift Monitor PSI > 0.25)
 *  - shadow:promoted    (shadow model promoted to production)
 *  - trade:opened       (new trade opened)
 *  - trade:closed       (trade closed)
 *
 * Connect from client via: io("/?XTransformPort=3003")
 *
 * Port: 3003 (behind Caddy gateway)
 */
import { Server as HttpServer } from "http";
import { Server as IOServer } from "socket.io";

const PORT = 3003;

const httpServer = new HttpServer((req, res) => {
  if (req.url === "/health") {
    res.writeHead(200, { "Content-Type": "application/json" });
    res.end(JSON.stringify({ ok: true, port: PORT, ts: Date.now() }));
    return;
  }
  res.writeHead(200, { "Content-Type": "application/json" });
  res.end(JSON.stringify({ service: "presidin-realtime", port: PORT }));
});

const io = new IOServer(httpServer, {
  cors: { origin: "*", methods: ["GET", "POST"] },
  path: "/",
});

interface Client {
  id: string;
  subscriptions: Set<string>;
}

const clients = new Map<string, Client>();

io.on("connection", (socket) => {
  console.log(`[realtime] client connected: ${socket.id}`);
  clients.set(socket.id, { id: socket.id, subscriptions: new Set(["all"]) });

  socket.on("subscribe", (channel: string) => {
    const c = clients.get(socket.id);
    if (c) c.subscriptions.add(channel);
    socket.emit("subscribed", { channel, ts: Date.now() });
  });

  socket.on("unsubscribe", (channel: string) => {
    const c = clients.get(socket.id);
    if (c) c.subscriptions.delete(channel);
    socket.emit("unsubscribed", { channel, ts: Date.now() });
  });

  // Allow clients to broadcast events (for dev / testing)
  socket.on("broadcast", (payload: { channel: string; data: any }) => {
    if (!payload?.channel) return;
    for (const c of clients.values()) {
      if (c.subscriptions.has("all") || c.subscriptions.has(payload.channel)) {
        io.to(c.id).emit(payload.channel, payload.data);
      }
    }
  });

  socket.on("disconnect", () => {
    console.log(`[realtime] client disconnected: ${socket.id}`);
    clients.delete(socket.id);
  });
});

// Demo broadcaster — emits a synthetic signal every 30 seconds
setInterval(() => {
  const symbols = ["EURUSD", "GBPUSD", "USDJPY", "XAUUSD", "BTCUSD"];
  const directions = ["BUY", "SELL", "NEUTRAL"];
  const signal = {
    id: `sig_${Date.now()}`,
    symbol: symbols[Math.floor(Math.random() * symbols.length)],
    direction: directions[Math.floor(Math.random() * directions.length)],
    confidence: 50 + Math.random() * 45,
    consensus: (Math.random() - 0.5) * 100,
    timestamp: Date.now(),
  };
  for (const c of clients.values()) {
    if (c.subscriptions.has("all") || c.subscriptions.has("signals:new")) {
      io.to(c.id).emit("signals:new", signal);
    }
  }
}, 30_000);

httpServer.listen(PORT, () => {
  console.log(`[presidin-realtime] listening on :${PORT}`);
});
