export const FONT_CATALOG = [
  ["system", "System", "system-ui"], ["rounded", "Rounded", "ui-rounded"], ["mono", "Terminal", "ui-monospace"], ["inter", "Inter", "Inter, system-ui"], ["roboto", "Roboto", "Roboto, sans-serif"], ["sf-pro", "SF Pro", "-apple-system, BlinkMacSystemFont"], ["segoe", "Segoe UI", "Segoe UI, sans-serif"], ["helvetica", "Helvetica Neue", "Helvetica Neue, sans-serif"], ["avenir", "Avenir", "Avenir, sans-serif"], ["futura", "Futura", "Futura, sans-serif"],
  ["geist", "Geist", "Geist, system-ui"], ["manrope", "Manrope", "Manrope, sans-serif"], ["dm-sans", "DM Sans", "DM Sans, sans-serif"], ["space-grotesk", "Space Grotesk", "Space Grotesk, sans-serif"], ["plus-jakarta", "Plus Jakarta", "Plus Jakarta Sans, sans-serif"], ["outfit", "Outfit", "Outfit, sans-serif"], ["sora", "Sora", "Sora, sans-serif"], ["urbanist", "Urbanist", "Urbanist, sans-serif"], ["poppins", "Poppins", "Poppins, sans-serif"], ["montserrat", "Montserrat", "Montserrat, sans-serif"],
  ["lato", "Lato", "Lato, sans-serif"], ["open-sans", "Open Sans", "Open Sans, sans-serif"], ["nunito", "Nunito", "Nunito, sans-serif"], ["quicksand", "Quicksand", "Quicksand, sans-serif"], ["raleway", "Raleway", "Raleway, sans-serif"], ["work-sans", "Work Sans", "Work Sans, sans-serif"], ["barlow", "Barlow", "Barlow, sans-serif"], ["oswald", "Oswald", "Oswald, sans-serif"], ["bebas", "Bebas Neue", "Bebas Neue, sans-serif"], ["titillium", "Titillium Web", "Titillium Web, sans-serif"],
  ["source-sans", "Source Sans", "Source Sans 3, sans-serif"], ["noto-sans", "Noto Sans", "Noto Sans, sans-serif"], ["public-sans", "Public Sans", "Public Sans, sans-serif"], ["lexend", "Lexend", "Lexend, sans-serif"], ["atkinson", "Atkinson", "Atkinson Hyperlegible, sans-serif"], ["ibm-plex", "IBM Plex", "IBM Plex Sans, sans-serif"], ["jetbrains", "JetBrains Mono", "JetBrains Mono, monospace"], ["fira-code", "Fira Code", "Fira Code, monospace"], ["source-code", "Source Code", "Source Code Pro, monospace"], ["inconsolata", "Inconsolata", "Inconsolata, monospace"],
  ["cascadia", "Cascadia", "Cascadia Code, monospace"], ["roboto-mono", "Roboto Mono", "Roboto Mono, monospace"], ["space-mono", "Space Mono", "Space Mono, monospace"], ["ibm-plex-mono", "IBM Plex Mono", "IBM Plex Mono, monospace"], ["courier", "Courier", "Courier New, monospace"], ["serif", "Serif", "ui-serif"], ["georgia", "Georgia", "Georgia, serif"], ["playfair", "Playfair", "Playfair Display, serif"], ["merriweather", "Merriweather", "Merriweather, serif"], ["lora", "Lora", "Lora, serif"],
  ["fraunces", "Fraunces", "Fraunces, serif"], ["crimson-text", "Crimson Text", "Crimson Text, serif"], ["libre-baskerville", "Libre Baskerville", "Libre Baskerville, serif"], ["cormorant", "Cormorant", "Cormorant Garamond, serif"], ["bitter", "Bitter", "Bitter, serif"], ["zilla-slab", "Zilla Slab", "Zilla Slab, serif"], ["space-serif", "Space Serif", "Space Serif, serif"], ["spectral", "Spectral", "Spectral, serif"], ["eczar", "Eczar", "Eczar, serif"], ["newsreader", "Newsreader", "Newsreader, serif"],
  ["archivo", "Archivo", "Archivo, sans-serif"], ["archivo-black", "Archivo Black", "Archivo Black, sans-serif"], ["anton", "Anton", "Anton, sans-serif"], ["rajdhani", "Rajdhani", "Rajdhani, sans-serif"], ["orbitron", "Orbitron", "Orbitron, sans-serif"], ["exo2", "Exo 2", "Exo 2, sans-serif"], ["chakra-petch", "Chakra Petch", "Chakra Petch, sans-serif"], ["saira", "Saira", "Saira, sans-serif"], ["teko", "Teko", "Teko, sans-serif"], ["russo-one", "Russo One", "Russo One, sans-serif"],
  ["syne", "Syne", "Syne, sans-serif"], ["unbounded", "Unbounded", "Unbounded, sans-serif"], ["red-hat", "Red Hat Display", "Red Hat Display, sans-serif"], ["figtree", "Figtree", "Figtree, sans-serif"], ["hanken", "Hanken Grotesk", "Hanken Grotesk, sans-serif"], ["schibsted", "Schibsted Grotesk", "Schibsted Grotesk, sans-serif"], ["albert-sans", "Albert Sans", "Albert Sans, sans-serif"], ["onest", "Onest", "Onest, sans-serif"], ["instrument", "Instrument Sans", "Instrument Sans, sans-serif"], ["general-sans", "General Sans", "General Sans, sans-serif"],
] as const;
export type FontProfile = typeof FONT_CATALOG[number][0];
export const FontNames = FONT_CATALOG.map(([id]) => id) as FontProfile[];
export function fontFamilyFor(profile: FontProfile): string { return FONT_CATALOG.find(([id]) => id === profile)?.[2] ?? "system-ui"; }
